Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from prfm.prfm import *
import matplotlib.pyplot as plt
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mprfm[39;00m[38;5;21;01m.[39;00m[38;5;21;01mprfm[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

File [0;32m~/work/PRFM/PRFM/book/../prfm/prfm.py:289[0m
[1;32m    285[0m     h [38;5;241m=[39m [38;5;241m2[39m[38;5;241m*[39mnp[38;5;241m.[39msqrt([38;5;241m-[39mQ)[38;5;241m*[39mnp[38;5;241m.[39mcos(theta[38;5;241m/[39m[38;5;241m3[39m)[38;5;241m-[39ma2[38;5;241m/[39m[38;5;241m3.[39m
[1;32m    287[0m     [38;5;28;01mreturn[39;00m h[38;5;241m*[39mH_gas_only
[0;32m--> 289[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01moptimize[39;00m [38;5;28;01mimport[39;00m root, brentq
[1;32m    290[0m [38;5;129m@np[39m[38;5;241m.[39mvectorize
[1;32m    291[0m [38;5;28;01mdef[39;00m [38;5;21mget_scale_height_numerical[39m(Sigma_gas, Sigma_star, Omega_d, H_star, sigma_eff,
[1;32m    292[0m                                zeta_d[38;5;241m=[39m[38;5;241m1[39m[38;5;241m/[39m[38;5;241m3.[39m, wgas[38;5;241m=[39m[38;5;241m1[39m, wstar[38;5;241m=[39m[38;5;241m1[39m, wdm[38;5;241m=[39m[38;5;241m1[39m):
[1;32m    293[0m [38;5;250m    [39m[38;5;124;03m"""Numerical solution of the vertical dynamical equilibrium equation[39;00m
[1;32m    294[0m [38;5;124;03m    including all weight terms.[39;00m
[1;32m    295[0m 
[1;32m    296[0m [38;5;124;03m    All inputs must be in c.g.s. units[39;00m
[1;32m    297[0m [38;5;124;03m    """[39;00m

[0;31mModuleNotFoundError[0m: No module named 'scipy'

